version: '3.7'
services:
  influxdb:
    build:
      context: ./influxdb/image
      dockerfile: Dockerfile
    image: influxdb
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=${AUTH_ENABLED}
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=pass
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=secretpasstelegraf
      - INFLUXDB_READ_USER=chronograf
      - INFLUXDB_READ_USER_PASSWORD=secretpasschornograf
    volumes:
      # Mount for influxdb data directory
      - ./influxdb/data:/var/lib/influxdb
    ports:
      - 8086:8086
      - 8082:8082
      # UDP Port
      - 8089:8089/udp
    networks:
      - influxdb

  telegraf:
    build:
      context: ./telegraf/image
      dockerfile: Dockerfile
    image: telegraf
    environment:
      - HOSTNAME=telegraf
    volumes:
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
      # log path for parser
      - ./telegraf/data:/var/data
    depends_on:
      - influxdb
    networks:
      - influxdb

  kapacitor:
    build:
      context: ./kapacitor/image
      dockerfile: Dockerfile
    image: kapacitor
    volumes:
      # Mount for kapacitor data directory
      - ./kapacitor/data/:/var/lib/kapacitor
    ports:
      - 9092:9092
    networks:
      - influxdb

  chronograf:
    build:
      context: ./chronograf/image
      dockerfile: Dockerfile
    image: chronograf
    environment:
      - RESOURCES_PATH=/usr/share/chronograf/resources
    volumes:
      # Mount for chronograf database
      - ./chronograf/data/:/var/lib/chronograf/
    networks:
      - influxdb
    ports:
      - 80:8888
    depends_on:
      - kapacitor
      - influxdb
      - telegraf

networks:
  influxdb:
    name: tick-stack
    driver: bridge